language: bash

sudo: required
dist: trusty

#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

#jdk: oraclejdk8
#https://github.com/travis-ci/travis-ci/issues/6371
#before_install:
#  - jdk_switcher use oraclejdk8

install:
#  - sudo apt-get install oracle-java8-set-default

## see https://askubuntu.com/questions/190582/installing-java-automatically-with-silent-option
  - sudo apt-get update
  - sudo apt-get install -y python-software-properties
#  - sudo add-apt-repository -y ppa:webupd8team/java
#  - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
#  - sudo apt-get install -y oracle-java8-installer

  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update
  - sudo apt-get install openjdk-8-jdk
  # workaround for missing cacerts in openjdk
  - sudo dpkg --purge --force-depends ca-certificates-java
  - sudo apt-get install ca-certificates-java

#  - sudo apt-get install -y openjdk-8-jdk
  - sudo apt-get install -y curl unzip zip wget

  ## install sdkman (see http://sdkman.io/install.html)
  - bash -c "curl -s "https://get.sdkman.io" | bash"
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"

  ## install kotlin and maven
#  - bash -c 'source "/home/travis/.sdkman/bin/sdkman-init.sh"; yes | sdk install java 8u144-oracle'
#  - bash -c 'source "/home/travis/.sdkman/bin/sdkman-init.sh"; yes | sdk install java 8u144-zulu'
#  - sudo apt-get install -y openjdk-8-jdk
  - sdk install maven
  - sdk install kotlin
  - sdk install gradle

  ## install assert.h
  - wget https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh && chmod +x assert.sh

  - export KSCRIPT_HOME="/home/travis/build/holgerbrandl/kscript"
  - pwd
  - export PATH=$KSCRIPT_HOME::$PATH

  # build it
  - cd $KSCRIPT_HOME && gradle shadowJar && cp build/libs/kscript-0.1-SNAPSHOT-all.jar kscript.jar


  - which kscript
  - which assert.sh

  ## does it run outside of test-suite?
  - kscript --help
  - java  -version
  - mvn --version
  - kscript 'println("kotlin rocks")'
  - kscript ${KSCRIPT_HOME}/test/resources/multi_line_deps.kts
#  - resdeps.kts org.org.docopt:org.docopt:0.6.0-SNAPSHOT log4j:log4j:1.2.14
#  - kscript ${KSCRIPT_HOME}/test/resources/multi_line_deps.kts

script: ./test/test_suite.sh

